version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - docker.env
    ports:
    - "3000:3000"
    restart: 'on-failure'
    deploy:
      replicas: 1
      restart: 'on-failure'
    depends_on:
    - db
  db:
    image: postgres
    environment:
    - POSTGRES_USER=value
    - POSTGRES_PASSWORD=value
    volumes:
    - postgres_data:/var/lib/postgres/data
    deploy:
      replicas: 1
      restart: 'on-failure'
    healthcheck:
      test: [ "pg_isready" ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  postgres_data:
